server {
    listen 80;
    listen [::]:80;
    server_name xmr-miner.whoamisec.com;
    
    root /var/www/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location /api {
        proxy_pass http://localhost:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /admin {
        try_files $uri $uri/ /admin.html;
    }
}

server {
    listen 443 ssl;
    server_name xmr-miner.whoamisec.com;
    
    ssl_certificate /etc/letsencrypt/live/whoamisec.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/whoamisec.com/privkey.pem;
    
    root /var/www/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }
    
    location /api {
        proxy_pass http://localhost:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
